### ISSUE TITLE
Support importing and rendering external React components

### ISSUE THREAD

**Issue by tomwayson** [alexlafroscia/ember-react-components#23] opened 2018-09-28 22:40 UTC
@alexlafroscia this addon is really great, and provides a very easy and fun way to write React components in an ember application.

However, I've been having trouble using React components from other packages distributed as UMD libraries.

For example, as a quick and dirty test, I tried to use `<StarRatingComponent />` from https://www.npmjs.com/package/react-star-rating-component, by `npm install`ing it and then `app.import`ing it's UMD build in `ember-cli-build.js`:

```js
 app.import('node_modules/react-star-rating-component/dist/react-star-rating-component.js');
```

I can see that file is successfully appended to `vendor.js`, however, when I run `ember s` I see a blank white screen and an `Uncaught TypeError: Cannot read property 'Component' of undefined` error in the console:

![image](https://user-images.githubusercontent.com/662944/46235167-f9ff4180-c32d-11e8-8e7e-b54957e9c7b5.png)

Which lead me to check if `window.React` was defined, and I was surprised to discover that it is not.

So then I tried loading that package "the right(er?) way" by removing the above `app.import()` and using [ember-auto-import](https://github.com/ef4/ember-auto-import). I then generated a new React component with:

```js
import React from 'react';
import WithEmberSupport from 'ember-react-components';
import StarRatingComponent from 'react-star-rating-component';

@WithEmberSupport
export default class TestRating extends React.Component {
  render() {
    return <div>
      <StarRatingComponent name="test" value={1} starCount={3} />
    </div>;
  }
}
``` 

I got a little further this time - the app at least loaded and worked until I got to the route where I invoked the above component I got a `Uncaught TypeError: Cannot read property 'unstable_cancelScheduledWork' of undefined`:

![image](https://user-images.githubusercontent.com/662944/46235540-89f1bb00-c32f-11e8-86cf-b40e42dbbecc.png)

My ultimate goal is to be able to load and use my own React components that I author in another package (so that they can be shared w/ other teams that are writing React apps). I only chose react-star-rating-component b/c it seemed like it would be compatible, but if you have a different example that you know works that would be great.

**Comment by alexlafroscia** [comment] 2018-09-28 23:15
No, I haven't really gone down the "support external react components" rabbit-hole yet, but would like to support that if I can!

I'm glad that you went and tried `ember-auto-import` yourself, because that was going to be my first suggestion. I'm happy that that cleared up at least _some_ of the issues you faced. I should really convert this addon to leverage `auto-import` under the hood, too...

Thank you for such a detailed issue for me to use as a starting place. When I get some time, I'll try to write some tests around rendering that star-rating component and see if I can get this to work!

**Comment by tomwayson** [comment] 2018-09-29 00:12
Me too.

That said, I've got it working w/ ember-cli-react:

![image](https://user-images.githubusercontent.com/662944/46237911-697c2d80-c33c-11e8-8428-fc3546553f5e.png)

Here's what I have installed in my `ember-cli-react` ember app:

```
ember-cli-react-test git:(master) ✗ yarn list --pattern=ember-auto-import      
yarn list v1.9.4
└─ ember-auto-import@1.2.13
✨  Done in 0.74s.
➜  ember-cli-react-test git:(master) ✗ yarn list --pattern=react
yarn list v1.9.4
├─ babel-helper-builder-react-jsx@6.26.0
├─ babel-plugin-transform-react-display-name@6.25.0
├─ babel-plugin-transform-react-jsx-self@6.22.0
├─ babel-plugin-transform-react-jsx-source@6.22.0
├─ babel-plugin-transform-react-jsx@6.24.1
├─ babel-preset-react@6.24.1
├─ broccoli-react@0.8.0
├─ create-react-class@15.6.3
├─ ember-cli-react@1.0.0
│  ├─ react-dom@15.6.2
│  └─ react@15.6.2
├─ react-dom@16.5.2
├─ react-star-rating-component@1.4.1
└─ react@16.5.2
✨  Done in 0.73s.
```

Here's what I have installed in my ember-react-components Ember app:

```
➜  ember-react-test git:(chore/use-hub-react-components) yarn list --pattern=ember-auto-import
yarn list v1.9.4
└─ ember-auto-import@1.2.13
✨  Done in 0.72s.
➜  ember-react-test git:(chore/use-hub-react-components) yarn list --pattern=react            
yarn list v1.9.4
├─ babel-helper-builder-react-jsx@6.26.0
├─ babel-plugin-transform-react-jsx@6.24.1
├─ ember-react-components@2.0.2
├─ react-dom@16.5.2
├─ react-star-rating-component@1.4.1
└─ react@16.5.2
✨  Done in 0.74s.
```

**Comment by alexlafroscia** [comment] 2018-09-29 01:46
So with `ember-cli-react` it "just works"?

**Comment by alexlafroscia** [comment] 2018-09-29 06:09
Very interesting. The rendering code between them is nearly the same, or was when I wrote this addon at least!

I’ll do the `auto-import` thing tomorrow and see if that fixes the issues you’re seeing. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by alexlafroscia** [comment] 2018-09-29 21:11
This is going to get held up a bit by this issue:

https://github.com/ef4/ember-auto-import/issues/119

Right now `ember-react-components` needs to support both Babel 6 and 7, providing the correct babel plugin based on which version of `ember-cli-babel` the host has installed. This works fine. The problem is that `ember-auto-import` uses that list of babel plugins and runs them against what's imported through Webpack within that addon -- this becomes a problem because `ember-auto-import` _only_ supports Babel 6 right now, so it chokes on Babel 7 plugins.

**Comment by alexlafroscia** [comment] 2018-09-29 21:44
You can check out the work that I started here:

https://github.com/alexlafroscia/ember-react-components/tree/ember-auto-import

For some reason, `ember-auto-import` does not seem to recognize `react` or `react-dom` as libraries that it should import... I'm not sure why. I've never had that problem with `ember-auto-import` in the past, and I have other addons that use it under-the-hood.

**Comment by alexlafroscia** [comment] 2018-09-29 22:06
I'm also seeing some additional issues, if I use Babel 6 (which you can do pretty easily with the way this addon is configured through `ember-try`:

```bash
ember try:one babel-6 --- ember test
```

https://github.com/ef4/ember-auto-import/issues/131

**Comment by mrblueblue** [comment] 2018-10-18 18:06
Just to update this thread with my experience: I was able to get an external React component working with this library using `ember-auto-import`. I don't think I have any special configuration, but I did add this to `ember-cli-build.js`:

```
    autoImport: {
      exclude: ['raven', 'react', 'react-dom', 'graphql']
    },
```

Let me know what other details I can provide to help!

**Comment by alexlafroscia** [comment] 2019-02-01 06:10
Thanks for your patience here!

`ember-auto-import` now supports the things that were holding it up before. I had to drop TypeScript, but we're not using `ember-auto-import` under the hood.

I just released `2.0.3` that swaps that out under the hood. @alejomo and @tomwayson, if either of you get a chance, can you check and see if that fixes your issues with third-party React components?

**Comment by alejomo** [comment] 2019-02-01 18:17
it works!!! the issue with the decorators was not related to the addon, I had to use the decorator as: export default WithEmberSupport(SayHi); thanks to @pzuraq in the e-decorators channel.

**Comment by alexlafroscia** [comment] 2019-02-01 23:30
That's... interesting.

The way you wrote it at first _should_ work. We have a bunch of tests around that case.

Would you mind opening a bug with the dependencies you had installed and what error you saw?

**Comment by alejomo** [comment] 2019-02-01 23:31
> @alejomo to clarify, before closing -- you were able to get your third-party React component rendering with the version I released yesterday?

Yes! really nice, I'm still playing with it, that's how I found the issue with the arrow function, I'm using https://github.com/OfficeDev/office-ui-fabric-react; but looks like it will work with any other component library.

**Comment by pzuraq** [comment] 2019-02-02 01:07
@alexlafroscia I believe the decorators spec changed pretty significantly for stage 2, that's probably why

**Comment by alexlafroscia** [comment] 2019-02-02 07:41
Great @alejomo -- I'll close this issue and look into why the decorator didn't work the way it should

@pzuraq -- good point! I'll upgrade this to the latest `babel-transforms` and make sure it works with Stage 2 decorators.

**Closed by alexlafroscia** 2019-02-02 07:41 UTC
Labels: enhancement
